#!/usr/bin/env python3
"""Build the ducted-kort propeller and nozzle FROM THE COMMITTED TABLES.

The first model in this repo generated by a script rather than by hand. Every
dimension is read from cad/underwater/ducted-kort/*.csv; nothing is invented here.

Conventions are taken from cad/CONVENTIONS.md, and this script deliberately does NOT
repeat the four defects found in the prior art at _work/tools/propgen.py:
  1. sections are mapped onto the CYLINDER of radius r, not placed flat and tangential
     (the underwater brief forbids the flat shortcut that the aerial brief allows);
  2. the generator line is at 50% chord, marine convention, not quarter chord;
  3. radius lies in XY with thrust along +Z, not radius along Y;
  4. tessellation is 0.05 mm, not 0.35 mm.

    python3 cad/tools/build_ducted_kort.py                  # the catalogue model, D = 250
    python3 cad/tools/build_ducted_kort.py --diameter 100   # the same design, your size

The tables are dimensioned for a 250 mm propeller. Scaling them is legitimate because they
are written as RATIOS of the diameter (c/D, t/D, P/D, r/R) -- which is the entire reason
model series are published that way. What does NOT scale is the water: a 100 mm propeller
at the same rpm runs at a quarter the Reynolds number and a quarter the tip speed. The
geometry is right; the performance is a different question, and nothing in this
repository has been validated against a physical measurement.
"""
import argparse, csv, math, os, sys
import cadquery as cq

HERE = os.path.dirname(os.path.abspath(__file__))
D_DIR = os.path.normpath(os.path.join(HERE, "..", "underwater", "ducted-kort"))

def table(name):
    with open(os.path.join(D_DIR, name)) as f:
        return list(csv.DictReader(l for l in f if not l.lstrip().startswith("#")))

def interp(xs, ys, x):
    if x <= xs[0]: return ys[0]
    if x >= xs[-1]: return ys[-1]
    for i in range(len(xs)-1):
        if xs[i] <= x <= xs[i+1]:
            f = (x-xs[i])/(xs[i+1]-xs[i]); return ys[i]+f*(ys[i+1]-ys[i])
    return ys[-1]

# ---------------------------------------------------------------- parameters
# D_REF is the diameter the committed tables are dimensioned at -- see the header of
# blade-planform.csv ("From the brief: D = 250 mm"). Every length below is derived from
# the requested diameter, so the defaults reproduce the catalogue model exactly.
D_REF      = 250.0          # diameter the tables were written for, mm
L_D        = 0.5            # nozzle length / diameter, from the brief
DEFLECTION = 0.05           # briefs' tessellation tolerance

D          = D_REF          # propeller/nozzle nominal diameter, mm  (--diameter)
NOZZLE_ID  = D_REF          # nozzle inner diameter at the throat    (--nozzle-id)
TIP_GAP    = 1.5            # brief: 1.5 mm, ~0.6% of D              (--tip-gap)
Z_BLADES   = 4              # blade count                            (--blades)
L          = L_D*D          # nozzle length
REF_R      = NOZZLE_ID/2    # 19A ordinates are measured from prop radius + clearance
TIP_R      = REF_R - TIP_GAP

def configure(diameter=D_REF, nozzle_id=None, tip_gap=1.5, blades=4):
    """Set the build parameters. Call before building anything.

    Kept as module globals rather than threaded through every function: this is a script
    that builds one propeller per run, and the geometry functions read like the tables do.
    """
    global D, NOZZLE_ID, TIP_GAP, Z_BLADES, L, REF_R, TIP_R
    D         = float(diameter)
    NOZZLE_ID = float(nozzle_id) if nozzle_id else D
    TIP_GAP   = float(tip_gap)
    Z_BLADES  = int(blades)
    L         = L_D*D
    REF_R     = NOZZLE_ID/2
    TIP_R     = REF_R - TIP_GAP
    if TIP_R <= 0:
        sys.exit(f"ERROR: tip clearance {TIP_GAP} mm leaves no propeller inside a "
                 f"{NOZZLE_ID} mm nozzle.")
    if Z_BLADES < 2:
        sys.exit(f"ERROR: {Z_BLADES} blades is not a propeller.")

# ------------------------------------------------------------------- nozzle
def nozzle():
    """Revolve the real 19A ordinates about +Z.

    duct-19a.csv gives x/L and the inner/outer ordinates as PERCENTAGES OF L,
    measured from (propeller radius + tip clearance). The outer contour is marked
    'straight_outer' over its straight run, where the source tabulates no ordinate;
    those stations are filled by linear interpolation between the last tabulated
    outer point and the trailing edge, exactly as the CSV header instructs.
    """
    rows = table("duct-19a.csv")
    xs   = [float(r["x_L_pct"]) for r in rows]
    yin  = [float(r["y_inner_L_pct"]) for r in rows]
    ox   = [float(r["x_L_pct"]) for r in rows if r["y_outer_L_pct"]]
    oy   = [float(r["y_outer_L_pct"]) for r in rows if r["y_outer_L_pct"]]

    def z_of(xp):  return -L/2 + (xp/100.0)*L
    def r_in(xp):  return REF_R + interp(xs, yin, xp)/100.0*L
    def r_out(xp): return REF_R + interp(ox, oy, xp)/100.0*L

    inner = [(r_in(x), z_of(x)) for x in xs]
    outer = [(r_out(x), z_of(x)) for x in xs]
    pts = inner + outer[::-1]                       # closed annular section
    wp = cq.Workplane("XZ").moveTo(*pts[0])
    for p in pts[1:]:
        wp = wp.lineTo(*p)
    # NOTE: revolve()'s axis is in LOCAL workplane coordinates. On the "XZ" plane the
    # local Y axis IS the global Z axis, so (0,1,0) spins about the shaft line. Passing
    # (0,0,1) here silently revolves about global Y and yields a zero-volume shape -
    # verified against the analytic annulus volume before trusting it.
    return wp.close().revolve(360, (0, 0, 0), (0, 1, 0))

# -------------------------------------------------------------------- blade
def ka_section(n=48):
    """Chordwise half-thickness of the Ka section, as a fraction of t_max.

    Suction side comes from the real Ka table (ka-sections.csv), which tabulates
    offsets at 20/40/60/80/90% of the distance from the maximum-thickness position
    to the LEADING edge, as percentages of t_max.

    The PRESSURE side is printed in the source for r/R 0.2-0.5 only - a defect
    recorded in that file. Rather than extrapolate data that does not exist, the
    pressure face is modelled FLAT, which is the classic Ka/Kaplan form. Stated here
    so it is visible, not buried.
    """
    rows = [r for r in table("ka-sections.csv") if r["side"] == "suction"]
    rr   = [float(r["r_R"]) for r in rows]
    cols = [("p20", 0.20), ("p40", 0.40), ("p60", 0.60), ("p80", 0.80), ("p90", 0.90)]
    def suction_at(r_R):
        # fraction of t_max at each fractional distance toward the LE
        return [(f, interp(rr, [float(x[c]) for x in rows], r_R)/100.0) for c, f in cols]
    return suction_at

def blade_wire(r_R, r_mm, c_mm, beta_deg, t_mm, xt, suction_at):
    """One section wire, mapped onto the cylinder of radius r_mm.

    Generator line at 50% chord (cad/CONVENTIONS.md, marine). Section rotated by the
    face-pitch angle beta about that line, then each 2D point (chordwise s, thickness y)
    is mapped onto the cylinder: circumferential distance becomes the angle s/r.
    """
    prof = []
    le, te = -xt*c_mm, (1.0-xt)*c_mm          # chordwise extent about max thickness
    # suction side: max-thickness point toward the LE, then on to the LE itself
    sn = suction_at(r_R)
    pts_s = [(0.0, t_mm)] + [(-f*abs(le), v*t_mm) for f, v in sn] + [(le, 0.0)]
    # pressure side is flat: LE -> TE along y = 0
    pts_p = [(le, 0.0), (te, 0.0)]
    # suction from TE back to the max-thickness point
    pts_t = [(te, 0.0), (0.0, t_mm)]
    # Traversal: LE -> TE along the flat pressure face, up to the max-thickness point,
    # then forward along the suction side to the LE. The suction offsets are already
    # ordered max-thickness -> LE (f = 0.2 .. 0.9), so they must NOT be reversed;
    # reversing them makes the section cross itself and the loft comes out invalid.
    loop = pts_p + pts_t[1:] + pts_s[1:-1]
    # resample the closed loop and map to the cylinder
    out = []
    for s, y in loop:
        sr  = s - (0.5 - xt)*c_mm             # shift so s=0 is the 50% chord generator line
        b   = math.radians(beta_deg)
        sx  =  sr*math.cos(b) + y*math.sin(b)   # chordwise, in the cylinder surface
        zz  = -sr*math.sin(b) + y*math.cos(b)   # axial
        th  = sx / r_mm                          # CYLINDRICAL MAPPING, not a flat placement
        out.append(cq.Vector(r_mm*math.cos(th), r_mm*math.sin(th), zz))
    return cq.Wire.makePolygon(out, close=True)

def blade():
    rows = table("blade-planform.csv")
    suction_at = ka_section()
    # The table lists r_tip_mm for the reference build; its largest value IS the tip radius
    # the table was written at (123.5 mm = 250/2 - 1.5). Scaling by the ratio keeps the
    # default build bit-for-bit identical, because that ratio is exactly 1.0.
    tip_ref  = max(float(r["r_tip_mm"]) for r in rows)
    r_scale  = TIP_R / tip_ref
    # pitch_deg needs no scaling: beta = atan(P/(2*pi*r)) and both P and r scale with D,
    # so the face-pitch angle at a given r/R is the same at every diameter. That is what
    # makes P/D the useful number rather than P.
    wires = []
    for r in rows:
        r_R  = float(r["r_R"]);  r_mm = float(r["r_tip_mm"])*r_scale
        c_mm = float(r["c_D"])*D
        t_mm = float(r["t_D"])*D
        wires.append(blade_wire(r_R, r_mm, c_mm, float(r["pitch_deg"]), t_mm,
                                float(r["Xtmax_cr"]), suction_at))
    # ruled=False gives a smooth loft; the tip is left OPEN-ended square, not faired:
    # makeLoft caps the end wires flat, which is exactly the square Ka tip the brief wants.
    # Build the blade from EXPLICIT FACES rather than makeLoft.
    #
    # The section wires lie on cylinders, so they are NON-PLANAR by construction - which is
    # the marine convention the brief insists on. makeLoft caps its end wires with PLANAR
    # faces, and a planar face cannot close a non-planar wire, so it produced a solid that
    # reported invalid and exported a mesh with 58 open edges at the blade root and tip.
    #
    # Instead: ruled surfaces between consecutive sections, then an N-sided filled surface
    # to cap the root and the square tip, assembled into a shell and sewn into a solid.
    faces = []
    for w1, w2 in zip(wires, wires[1:]):
        rs = cq.Face.makeRuledSurface(w1, w2)
        faces.extend(rs.Faces() if hasattr(rs, "Faces") else [rs])
    for w in (wires[0], wires[-1]):
        faces.append(cq.Face.makeNSidedSurface(w.Edges(), []))
    # NOTE on scaling: the section wires scale EXACTLY with diameter (measured: 4e-16
    # relative deviation). These two cap surfaces do not - makeNSidedSurface fits a
    # surface by minimising an energy functional against absolute tolerances, which is
    # not scale-invariant. Net effect: blade volume tracks D^3 to about 0.25% rather
    # than exactly. It is the caps, not the tables. Measured, not assumed.
    shell = cq.Shell.makeShell(faces)
    return cq.Solid.makeSolid(shell)

# ---------------------------------------------------------------------- hub
def hub():
    # hub.csv is dimensioned in mm for D_REF; its own header records the ratios it came
    # from (hub ratio 0.265 of D, length 0.30 D), so a straight scale is faithful to it.
    s = D / D_REF
    d = {r["parameter"]: float(r["value"])*s for r in table("hub.csv")}
    return (cq.Workplane("XY")
            .circle(d["hub_dia_forward"]/2).workplane(offset=d["hub_length"])
            .circle(d["hub_dia_aft"]/2).loft()
            .translate((0, 0, -d["hub_length"]/2)))

def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Build a ducted Kort propeller from the committed Ka / 19A tables.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Defaults reproduce the catalogue model in cad/underwater/ducted-kort/.")
    ap.add_argument("--diameter", type=float, default=D_REF, metavar="MM",
                    help=f"propeller diameter in mm (default {D_REF:g})")
    ap.add_argument("--blades", type=int, default=4, metavar="Z",
                    help="number of blades (default 4)")
    ap.add_argument("--tip-gap", type=float, default=None, metavar="MM",
                    help="tip clearance in mm (default 0.6%% of diameter, as the brief)")
    ap.add_argument("--nozzle-id", type=float, default=None, metavar="MM",
                    help="nozzle inner diameter (default: same as --diameter)")
    ap.add_argument("--out", default=D_DIR, metavar="DIR",
                    help="output directory (default: the ducted-kort data folder)")
    ap.add_argument("--name", default="ducted_kort_propgen", metavar="STEM",
                    help="output file stem (default ducted_kort_propgen)")
    ap.add_argument("--separate", action="store_true",
                    help="also write the propeller and the nozzle as their own STLs, "
                         "which is what you need to print them")
    a = ap.parse_args(argv)

    # The brief's 1.5 mm gap on a 250 mm propeller is 0.6% of D. Hold the RATIO when
    # scaling, not the millimetres: the same 1.5 mm on a 100 mm propeller is 1.5% of D,
    # two and a half times the leakage the design was drawn around.
    tip_gap = a.tip_gap if a.tip_gap is not None else 1.5 * a.diameter / D_REF
    configure(a.diameter, a.nozzle_id, tip_gap, a.blades)

    gap_pct = 100.0 * TIP_GAP / D
    print(f"D {D:g} mm   Z {Z_BLADES}   nozzle ID {NOZZLE_ID:g} mm   "
          f"tip gap {TIP_GAP:.3f} mm ({gap_pct:.2f}% of D)   L {L:g} mm")
    if gap_pct > 1.0:
        print(f"WARNING: tip clearance is {gap_pct:.2f}% of D. The ducted-kort brief designs "
              f"for 0.6%\n         (1.5 mm on 250 mm). Above roughly 1% the leakage over the "
              f"tip starts to cost\n         real thrust -- that is general ducted-propeller "
              f"practice, not a rule this repo\n         asserts. Print clearance you cannot "
              f"hold is worse than clearance you design for.")

    noz = nozzle()
    b   = blade()
    prop = hub()
    for i in range(Z_BLADES):
        prop = prop.union(cq.Workplane(obj=b.rotate((0,0,0),(0,0,1), i*360.0/Z_BLADES)))
    os.makedirs(a.out, exist_ok=True)
    out_stl  = os.path.join(a.out, a.name + ".stl")
    out_step = os.path.join(a.out, a.name + ".step")
    compound = cq.Compound.makeCompound([prop.val(), noz.val()])
    cq.exporters.export(cq.Workplane(obj=compound), out_step)
    cq.exporters.export(cq.Workplane(obj=compound), out_stl,
                        tolerance=DEFLECTION*D/D_REF, angularTolerance=0.1)
    print(f"blade  volume {b.Volume():9.1f} mm3  valid={b.isValid()}")
    print(f"nozzle volume {noz.val().Volume():9.1f} mm3  valid={noz.val().isValid()}")
    print(f"prop   volume {prop.val().Volume():9.1f} mm3  valid={prop.val().isValid()}")
    bb = compound.BoundingBox()
    print(f"bbox  X {bb.xmin:.2f}..{bb.xmax:.2f}  Y {bb.ymin:.2f}..{bb.ymax:.2f}  Z {bb.zmin:.2f}..{bb.zmax:.2f}")
    print(f"wrote {out_stl}")
    print(f"wrote {out_step}")
    if a.separate:
        # The combined file holds two separate solids. A slicer can usually split them,
        # but they print as different parts with different orientations and supports, so
        # writing them out separately is less error-prone than asking the slicer.
        for part, shape in (("propeller", prop.val()), ("nozzle", noz.val())):
            f = os.path.join(a.out, f"{a.name}_{part}.stl")
            cq.exporters.export(cq.Workplane(obj=shape), f,
                                tolerance=DEFLECTION*D/D_REF, angularTolerance=0.1)
            print(f"wrote {f}")
    if not (b.isValid() and prop.val().isValid() and noz.val().isValid()):
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
