#!/usr/bin/env python3
"""Assert that every geometry table in this repository says where it came from.

The repository's promise to a beginner is not that its numbers are right. It is that
you can always tell WHICH numbers are right: what was transcribed from a published
source, what a script generated, and what was invented to be dimensionally consistent.
That promise is only worth something if it is enforced, so this is a build step, not a
convention.

`cad/tools/check-geometry.py` already checks provenance on the underwater tables. This
checks EVERY table -- aerial too -- and additionally checks the declaration block that
tells a reader what frame, units and pitch datum the numbers are in. A table of numbers
with no datum is not geometry; it is a spreadsheet.

    python3 cad/tools/check_provenance.py  # exits non-zero on any failure

Standard library only, on purpose: it has to run in CI without installing anything.
"""
import glob, os, re, sys

# This file lives in cad/tools/, so ".." is cad/ and dirname(ROOT) is the repository
# root - which is what the GENERATED BY paths in the headers are relative to.
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

# The four things a reader must know before a number in the file means anything.
# Every table in the repo already carries these; see cad/CONVENTIONS.md.
DECLARATIONS = ("FRAME", "UNITS", "PITCH", "AXIS")

# A citation has to be followable. Either a link, or a permanent identifier that a
# library can resolve. "Table 2 of a paper I read" is not a source.
LOCATOR = re.compile(r"https?://|arXiv:|AD\d{6,}|doi:|DOI\s|ISBN|Report\s+\d|NSRDC|NASA[- ]?(TM|CR|TP)", re.I)
# ...and it has to be dated, so a reader can tell how old the reading is and re-fetch it.
DATED = re.compile(r"(transcribed|fetched|downloaded|extracted|compiled|confirmed|read|copied)"
                   r"\D{0,20}(\d{4}-\d{2}-\d{2})", re.I)

fails, checks = [], 0

def ok(cond, label, detail=""):
    global checks
    checks += 1
    if not cond:
        fails.append(f"{label}  {detail}")
    return cond

def header(path):
    """The comment block at the top of the file, up to the first data line."""
    out = []
    with open(path) as f:
        for line in f:
            if not line.lstrip().startswith("#"):
                break
            out.append(line)
    return "".join(out)

csvs = sorted(glob.glob(os.path.join(ROOT, "*", "*", "*.csv")))
if not csvs:
    sys.exit(f"no CSVs found under {ROOT} - has the layout moved?")

for path in csvs:
    rel = os.path.relpath(path, os.path.dirname(ROOT))
    head = header(path)

    # ---- 1. the file declares its frame, units, pitch datum and generator axis ----
    for key in DECLARATIONS:
        ok(re.search(rf"^#\s*{key}\b", head, re.M) is not None,
           f"declares {key}: {rel}", "no such line in the header block")

    # ---- 2. the file says which kind of number it holds ----
    cited     = "Source:" in head or "SOURCE:" in head
    generated = "GENERATED BY" in head
    synthetic = "SYNTHETIC" in head
    ok(cited or generated or synthetic, f"provenance declared: {rel}",
       "needs a 'Source:' citation, a 'GENERATED BY' line, or a SYNTHETIC label")

    # ---- 3. a citation must be followable and dated ----
    if cited:
        ok(LOCATOR.search(head) is not None, f"citation is followable: {rel}",
           "no URL, arXiv/DTIC/DOI id or report number in the header")
        ok(DATED.search(head) is not None, f"citation is dated: {rel}",
           "no 'Transcribed/Fetched YYYY-MM-DD' in the header")

    # ---- 4. synthetic data must say what it is NOT ----
    # The failure mode this repo keeps hitting is a plausible-looking table being mistaken
    # for a real one. Saying "NOT a manufacturer's hub" out loud is what prevents it.
    if synthetic:
        ok("NOT " in head, f"SYNTHETIC says what it is not: {rel}",
           "add a line starting 'NOT ...' naming what this is not")

    # ---- 5. generated data must name the script, so it can be regenerated ----
    if generated:
        m = re.search(r"GENERATED BY\s+(\S+)", head)
        named = m.group(1).rstrip(".,") if m else None
        exists = bool(named) and os.path.exists(
            os.path.join(os.path.dirname(ROOT), named))
        ok(exists, f"generator script exists: {rel}",
           f"header names '{named}', which is not in the repository")

print(f"checked {checks} assertions across {len(csvs)} CSVs")
if fails:
    print(f"\n{len(fails)} FAILED:")
    for f in fails:
        print("  x " + f)
    sys.exit(1)
print("all pass")
