#!/usr/bin/env python3
"""Generate the GENERATED and SYNTHETIC geometry tables in cad/aerial/.

Mirrors cad/tools/make-geometry.py (underwater) but the RULES ARE DIFFERENT, and
that difference is deliberate:

  * The 1 mm minimum trailing-edge thickness is a WET-SPECIFIC rule. It appears
    under "Wet-specific" in cad/underwater_cad.md and nowhere in the aerial brief,
    which instead asks for a "sharp trailing edge" on the custom carbon blade.
    So aerial sections use the OPEN NACA form and are not blunted. Applying the
    marine floor here would be a category error.
  * Aerial blades are far thinner (t/c 14% root to 7-9% tip) than marine ones
    (~5% at 0.7R but 20%+ at the root, and cast in bronze).
  * Chord shape is benchmarked against the real APC 10x5E in
    cad/aerial/fixed-pitch/apc-10x5e.csv, the way the marine tables are
    benchmarked against DTMB 4119.

Deterministic: re-running rewrites byte-identical files.
    python3 cad/tools/make-aerial-geometry.py
"""
import math, os, io, csv

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "aerial"))
GEN  = "cad/tools/make-aerial-geometry.py"

def write(slug, name, header, cols, rows):
    with io.open(os.path.join(ROOT, slug, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(header.rstrip("\n") + "\n" + ",".join(cols) + "\n")
        for r in rows:
            f.write(",".join(f"{v:.6f}" if isinstance(v, float) else str(v) for v in r) + "\n")
    print(f"  {slug}/{name}  ({len(rows)} rows)")

# ---------------------------------------------------------------- NACA 4-digit
# Open trailing edge (-0.1015) on purpose: see the module docstring.
def naca4_thickness(x, t):
    return 5*t*(0.2969*math.sqrt(x) - 0.1260*x - 0.3516*x*x + 0.2843*x**3 - 0.1015*x**4)

def naca4_camber(x, m, p):
    if m == 0: return 0.0, 0.0
    if x < p:  return m/p**2*(2*p*x - x*x), 2*m/p**2*(p - x)
    return m/(1-p)**2*((1-2*p) + 2*p*x - x*x), 2*m/(1-p)**2*(p - x)

def cosine(n): return [(1-math.cos(math.pi*i/n))/2 for i in range(n+1)]

def naca4(code, n=80):
    m, p, t = int(code[0])/100, int(code[1])/10, int(code[2:])/100
    if p == 0: p = 0.1
    out=[]
    for x in cosine(n):
        yt = naca4_thickness(x, t); yc, dyc = naca4_camber(x, m, p)
        th = math.atan(dyc)
        out.append((x, yt, yc, x-yt*math.sin(th), yc+yt*math.cos(th),
                    x+yt*math.sin(th), yc-yt*math.cos(th)))
    return out, m, p, t

EQ = ("#   y_t = 5t(0.2969*sqrt(x) - 0.1260x - 0.3516x^2 + 0.2843x^3 - 0.1015x^4)\n"
      "# Abbott & von Doenhoff, 'Theory of Wing Sections' (Dover, 1959), Sec. 6.4.\n"
      "# OPEN trailing edge (-0.1015), kept sharp: the 1 mm TE floor in this repo is a\n"
      "# WET-SPECIFIC marine rule and does not apply to an aerial blade.")

print("GENERATED (published equations):")
for slug, name, code, role in [
    ("cyclorotor", "naca0015.csv", "0015",
     "symmetric blade section for the cyclorotor drum, pitch axis at 30% chord per the brief."),
    ("ducted-fan", "rotor-section-naca2408.csv", "2408",
     "thin high-solidity rotor section. 8% thick: a ducted fan rotor is thinner than an open "
     "propeller because the duct unloads the tip."),
    ("ducted-fan", "stator-vane-naca4412.csv", "4412",
     "cambered stator vane, V = 11. Camber is what recovers rotor swirl; a symmetric vane "
     "would straighten nothing."),
]:
    pts, m, p, t = naca4(code)
    write(slug, name,
          f"# NACA {code} - GENERATED BY {GEN}\n#\n"
          f"# Computed from the published NACA four-digit equations, not transcribed:\n{EQ}\n"
          f"# max camber m={m:.4f} at p={p:.2f}, thickness t={t:.4f}\n#\n# Role: {role}\n"
          f"# Exact and re-derivable. Regenerate rather than edit.",
          ["x_c","y_t","y_camber","x_upper","y_upper","x_lower","y_lower"], pts)

# ------------------- real APC chord shape, the aerial shape reference --------
def apc_shape():
    path = os.path.join(ROOT, "fixed-pitch", "apc-10x5e.csv")
    rows = list(csv.DictReader(l for l in open(path) if not l.startswith("#")))
    return [(float(r["r_R"]), float(r["c_D"])) for r in rows]
APC = apc_shape()
# Peak c/D of the real APC 10x5E. Synthetic aerial blades are scaled to match it rather
# than to an unexplained number, so their solidity is anchored to a real propeller.
APC_PEAK_CD = max(b for _, b in APC)

def interp(pairs, x):
    xs=[a for a,_ in pairs]; ys=[b for _,b in pairs]
    if x<=xs[0]: return ys[0]
    if x>=xs[-1]: return ys[-1]
    for i in range(len(xs)-1):
        if xs[i]<=x<=xs[i+1]:
            f=(x-xs[i])/(xs[i+1]-xs[i]); return ys[i]+f*(ys[i+1]-ys[i])
    return ys[-1]

def apc_chord_shape(xs):
    """Normalised chord following the real APC 10x5E blade over its aerodynamic span."""
    peak=max(b for _,b in APC)
    return [max(interp(APC, r)/peak, 0.02) for r in xs]

def stations(hub, n=21):
    return [hub + (1-hub)*i/(n-1) for i in range(n)]

print("\nSYNTHETIC (parametric, from each brief's own numbers):")

# ------------------------------------------------- custom carbon blade -------
CC=dict(D=254.0, Z=2, hub=0.15, shank_d=8.0, shank_len=15.0, t_root=0.12, t_tip=0.07,
        thrust_N=12.0, rpm=9000.0, v_inf=0.0, rho=1.225)
xs=stations(CC["hub"]); sh=apc_chord_shape(xs)
n=CC["rpm"]/60.0; R=CC["D"]/2000.0
def cc_twist(r):
    # blade-element: beta = phi + alpha, phi from the local helix at the design point
    Vt=2*math.pi*n*r*R; Va=CC["v_inf"]+0.5*math.sqrt(max(CC["thrust_N"],1e-6)/(0.5*CC["rho"]*math.pi*R*R))
    return math.degrees(math.atan2(Va, Vt))+4.0     # +4 deg design angle of attack
rows=[(r, sh[i]*APC_PEAK_CD, cc_twist(r), CC["t_root"]+(CC["t_tip"]-CC["t_root"])*((r-CC["hub"])/(1-CC["hub"])))
      for i,r in enumerate(xs)]
tipM=2*math.pi*n*R/340.3
write("custom-carbon","blade-planform.csv",
f"""# Custom carbon blade planform - SYNTHETIC, GENERATED BY {GEN}
#
# NOT a solved design point. The brief is explicit that this blade's planform should come
# from JavaProp, QPROP, XROTOR or JBLADE and arrive as a chord/twist CSV - "the CSV is the
# interface: a new design point is a new table, not a new script". Running one of those
# codes is out of scope here, so this is a stand-in with the SAME COLUMN SHAPE, so that a
# real solved table can replace it without touching any downstream script.
#
# Chord follows the real APC 10x5E distribution (../fixed-pitch/apc-10x5e.csv), scaled.
# Twist is blade-element: beta = atan(Va / Vt) + 4 deg angle of attack, with Va from simple
# momentum theory at the stated design point. That is a first estimate, not a solved design.
#
# DESIGN POINT (assumptions, recorded so they can be argued with):
#   thrust {CC['thrust_N']} N, {CC['rpm']:.0f} rpm, forward speed {CC['v_inf']} m/s (static),
#   rho {CC['rho']} kg/m3, D {CC['D']:.0f} mm, Z {CC['Z']}.
#   Tip Mach at this rpm = {tipM:.3f} (sea level, 340.3 m/s).
# Shank: {CC['shank_d']} mm diameter over {CC['shank_len']} mm, a true cylinder for clamping.
# Sections are thin ({CC['t_root']:.0%} root to {CC['t_tip']:.0%} tip) with a SHARP trailing edge,
# per the brief - no marine TE floor applies here.""",
["r_R","c_D","twist_deg","t_c"], rows)

# ------------------------------------------------------- eVTOL proprotor -----
EV=dict(D=1500.0, Z=5, hub=0.15, tipM_cap=0.55, blend=0.5,
        lam_hover=0.07, lam_cruise=0.55)   # inflow ratios Va/(Omega*R)
xs=stations(EV["hub"])
def xv15_chord(r):
    # XV-15 planform: 16.6 in at r/R 0.091 tapering linearly to 14 in at 0.25, then constant
    if r<=0.091: c=16.6
    elif r<0.25: c=16.6+(14.0-16.6)*(r-0.091)/(0.25-0.091)
    else: c=14.0
    return c/300.0                                   # /D, XV-15 D = 300 in
rows=[]
for r in xs:
    # local inflow angle phi = atan(lambda / (r/R)), lambda = Va/(Omega*R) the inflow ratio.
    # Dividing by (r/R), NOT by 2*pi*r: the 2*pi belongs in Omega, not in the radius.
    hover =math.degrees(math.atan(EV["lam_hover"] /r))+8.0    # induced inflow only
    cruise=math.degrees(math.atan(EV["lam_cruise"]/r))+2.0    # freestream dominates
    rows.append((r, xv15_chord(r), hover, cruise,
                 hover+(cruise-hover)*EV["blend"]))
write("evtol-proprotor","blend-twist.csv",
f"""# eVTOL proprotor chord and blended twist - SYNTHETIC, GENERATED BY {GEN}
#
# NOT a solved pair of design points. The brief wants two chord/twist tables from XROTOR or
# QPROP - one hover, one cruise - reconciled at a blend weight. This generates both twist
# distributions from simple blade-element inflow angles and blends them, so the STRUCTURE is
# right and the blend weight is live. Replace the two twist columns with solved tables.
#
# Chord follows the XV-15 planform (see xv15-reference.csv): constant outboard of r/R 0.25,
# tapering inboard. Real tiltrotor practice, scaled to this brief's D = {EV['D']:.0f} mm.
#
# INFLOW RATIOS (assumptions): lambda = Va/(Omega*R) = {EV['lam_hover']} hover, {EV['lam_cruise']} cruise. Cruise is
# coarser at every station because the freestream dominates the local helix angle; that is
# why a proprotor must compromise rather than pick one.
#
# THE BLEND WEIGHT IS THE DESIGN PROBLEM, per the brief: a blade optimal in hover is badly
# pitched in cruise and vice versa. blend = {EV['blend']} here; twist_blended is what gets built.
# Sweep it and watch twist_deg move - that is the trade being made.
#
# Tip Mach cap {EV['tipM_cap']} from the brief. At D = {EV['D']:.0f} mm that caps tip speed at
# {EV['tipM_cap']*340.3:.1f} m/s = {EV['tipM_cap']*340.3/(math.pi*EV['D']/1000)*60:.0f} rpm. Check any rpm choice against that.""",
["r_R","c_D","twist_hover_deg","twist_cruise_deg","twist_blended_deg"], rows)

# ------------------------------------------------------------ coaxial pair ---
CX=dict(D=254.0, Z=2, h_D=0.12, hub=0.15, PD=0.5)
xs=stations(CX["hub"]); sh=apc_chord_shape(xs)
a_ind=0.5*(math.sqrt(1+0.45)-1)
rows=[]
for i,r in enumerate(xs):
    up=math.degrees(math.atan(CX["PD"]/(math.pi*r)))
    lo=math.degrees(math.atan(CX["PD"]*(1+a_ind)/(math.pi*r)))
    rows.append(("upper", r, sh[i]*APC_PEAK_CD, CX["PD"], up, "right"))
    rows.append(("lower", r, sh[i]*APC_PEAK_CD, CX["PD"]*(1+a_ind), lo, "left"))
write("coaxial","rotor-pair.csv",
f"""# Coaxial contra-rotating pair - SYNTHETIC, GENERATED BY {GEN}
#
# NOT a solved design. The lower rotor's inflow is the upper rotor's downwash, which is the
# whole design problem - the same issue the marine CRP file carries, and it needs a real
# solver (QPROP/XROTOR), not a table.
#
# First-order actuator-disc estimate: axial induction a = 0.5(sqrt(1+CT)-1) = {a_ind:.4f} at an
# assumed CT = 0.45. The LOWER rotor sees inflow raised by (1+a), so it needs MORE pitch to
# hold the same angle of attack: P/D {CX['PD']} upper vs {CX['PD']*(1+a_ind):.4f} lower.
# Both rotors are D = {CX['D']:.0f} mm at spacing h = {CX['h_D']} D, per the brief.
#
# The brief's warning is the point: size the stack against what a coaxial pair actually
# delivers, not double a single rotor. Induced power climbs steeply as spacing shrinks and
# the pair lands well short of 2x thrust at equal power. This table does not model that -
# it only pitches the lower rotor for its own inflow.
# hand is a genuine XZ mirror, not a rotation.""",
["rotor","r_R","c_D","P_D","pitch_deg","hand"], rows)

# ------------------------------------------------------- ducted fan duct -----
DF=dict(fan_D=90.0, Z=5, V=11, hub=0.45, tip_gap=0.4, lip_r=6.0, exit_area=0.85)
def duct(n=41):
    Rf=DF["fan_D"]/2; lip=DF["lip_r"]/Rf
    rows=[]
    for i in range(n):
        x=i/(n-1)
        if x<0.15:                                   # rounded inlet lip
            u=x/0.15; ri=1+lip*(1-math.sqrt(max(0.0,1-(1-u)**2)))
        elif x<0.45: ri=1.0                          # cylindrical across the rotor plane
        else:                                        # exit nozzle: area ratio 0.85
            u=(x-0.45)/0.55
            r_exit=math.sqrt(DF["exit_area"])
            ri=1.0+(r_exit-1.0)*(3*u*u-2*u**3)
        rows.append((x, ri, ri+naca4_thickness(max(x,1e-9), 0.10)))
    return rows
d=duct()
rot_plane=[r for r in d if abs(r[1]-1.0)<1e-12]
write("ducted-fan","duct-ordinates.csv",
f"""# Ducted fan duct wall - SYNTHETIC, GENERATED BY {GEN}
#
# NOT Schuebeler or any production EDF geometry, which is commercial. Parametric, from the
# brief's numbers. Reference for method: NASA low-noise fan design,
# https://ntrs.nasa.gov/api/citations/20230003262/downloads/20230003262%20REV%20FINAL.pdf
#
# From the brief: fan D = {DF['fan_D']:.0f} mm, rotor Z = {DF['Z']}, stator V = {DF['V']}, hub ratio {DF['hub']},
#   tip clearance {DF['tip_gap']} mm (~0.5% of D), inlet lip radius {DF['lip_r']:.0f} mm,
#   exit nozzle area {DF['exit_area']:.0%} of swept area.
#
# TYLER-SOFRIN: V >= 2Z cuts off the fundamental blade-passing tone so it never propagates
# down the duct. Z = {DF['Z']} sets the floor at {2*DF['Z']}, hence V = {DF['V']}. Not "pick something coprime".
#
# Wall runs CYLINDRICAL across the rotor plane (x/L 0.15-0.45, {len(rot_plane)} stations at exactly
# 1.000) so tip clearance is uniform there - the same requirement the marine Kort nozzle has.
# Exit contracts to sqrt({DF['exit_area']}) = {math.sqrt(DF['exit_area']):.4f} of the fan radius, giving the area ratio.
# Radii are fractions of the FAN radius ({DF['fan_D']/2:.0f} mm). Sharp TE - aerial, no marine floor.""",
["x_L","r_inner_fanR","r_outer_fanR"], d)

# ----------------------------------------------- ducted fan rotor + stator ---
DF_TIP = (DF["fan_D"]/2 - DF["tip_gap"])/(DF["fan_D"]/2)     # tip pinned to the clearance
xs=stations(DF["hub"]); sh=apc_chord_shape(xs)
# A DUCTED rotor does not fair to a point - the duct carries the tip loading, so chord stays
# wide and the tip is cut square. Hold the outer chord instead of letting the APC taper run.
sh=[max(v, 0.75) for v in sh]
rows=[(r, r*DF_TIP, sh[i]*APC_PEAK_CD*2.2,
       math.degrees(math.atan(0.85/(math.pi*r))), 0.08) for i,r in enumerate(xs)]
write("ducted-fan","rotor-schedule.csv",
f"""# Ducted fan rotor schedule, Z = {DF['Z']} - SYNTHETIC, GENERATED BY {GEN}
#
# NOT a production EDF rotor - Schuebeler and the rest are commercial. Parametric, from the brief.
#
# THE NUMBER THIS FILE EXISTS TO PIN: the brief's {DF['tip_gap']} mm tip clearance on a {DF['fan_D']:.0f} mm fan puts
# the rotor tip at r_fanR = ({DF['fan_D']/2:.0f} - {DF['tip_gap']}) / {DF['fan_D']/2:.0f} = {DF_TIP:.4f} of fan radius. Without this
# column the clearance existed only as prose, and the duct wall had nothing to be checked
# against. r_fanR is the station radius as a fraction of the FAN radius - multiply by
# {DF['fan_D']/2:.0f} mm, and note duct-ordinates.csv uses the same reference so the two files compare
# directly at the rotor plane, where the wall runs exactly 1.0000.
#
# Hub ratio {DF['hub']} per the brief - much fatter than an open propeller, because a ducted fan
# needs the hub to house the motor and to keep the annulus area sensible.
# High solidity and thin ({0.08:.0%} t/c) sections: the duct unloads the tip, so the blade can be
# thinner than an open propeller and there is no marine thickness floor here.
# Chord follows the real APC 10x5E distribution over the inboard span, then is HELD outboard -
# a ducted rotor ends square, it does not taper to a point.""",
["r_R","r_fanR","c_D","pitch_deg","t_c"], rows)

# stator: V = 11 vanes, expressed as geometry rather than as a number in prose
V=DF["V"]
rows=[(i, i*360.0/V, DF["hub"], 1.0, 25.0) for i in range(V)]
write("ducted-fan","stator-vanes.csv",
f"""# Ducted fan stator vane set, V = {V} - SYNTHETIC, GENERATED BY {GEN}
#
# NOT a production EDF stator. Vane spacing and stagger here are parametric; the count is the
# part that follows a real rule.
#
# The vane COUNT is the design decision and it is not arbitrary. Tyler-Sofrin: V >= 2Z cuts off
# the fundamental blade-passing tone so it never propagates down the duct, and V >= 4Z holds
# that through the second harmonic. Z = {DF['Z']} sets the floor at {2*DF['Z']}, hence V = {V}. This is not
# "pick something coprime" - see the NASA low-noise fan design methods cited in the brief.
#
# Vanes are evenly spaced at {360.0/V:.3f} deg, run from the hub ({DF['hub']}) to the duct wall (1.0), and
# carry the motor pod - so they are structural as well as aerodynamic. Section is in
# stator-vane-naca4412.csv; stagger is the angle the chord makes with the axis.
# Vanes sit DOWNSTREAM of the rotor, per the brief.""",
["vane","angle_deg","r_inner_fanR","r_outer_fanR","stagger_deg"], rows)

# ------------------------------------------------------------- Q-tip bend ----
QT=dict(start=0.92, angle_brief=75.0, radius_mm=8.0, D=254.0)
# The brief over-specifies the bend: start r/R 0.92, radius 8 mm AND angle 75 deg are three
# constraints on two degrees of freedom. Arc length through 75 deg at 8 mm is 10.472 mm; the
# developed span 0.92->1.0 on a 254 mm blade is 10.160 mm - a 3.1% disagreement. Radius and
# span are the two that fix real geometry, so the ANGLE is derived from them here.
QT["angle"] = math.degrees((1-QT["start"])*(QT["D"]/2)/QT["radius_mm"])
def qtip(n=25):
    R=QT["D"]/2; rad=QT["radius_mm"]/R
    rows=[]
    for i in range(n+1):
        u=i/n; th=math.radians(QT["angle"])*u
        r=QT["start"]+rad*math.sin(th)               # radius stops growing as it bends
        z=-rad*(1-math.cos(th))                      # aft (negative z)
        rows.append((u, QT["start"]+(1-QT["start"])*u, r, z, math.degrees(th)))
    return rows
q=qtip(); proj=q[-1][2]
write("q-tip","bend-path.csv",
f"""# Q-tip bend path - SYNTHETIC, GENERATED BY {GEN}
#
# NOT Hartzell Q-Tip geometry, which is proprietary. Parametric, from the brief.
#
# From the brief: bend starts at r/R = {QT['start']}, bend radius {QT['radius_mm']:.0f} mm, D = {QT['D']:.0f} mm.
# ANGLE IS DERIVED, NOT TAKEN FROM THE BRIEF: theta = span / radius = {QT['angle']:.3f} deg, against the
# brief's stated {QT['angle_brief']:.0f} deg. The brief gives three constraints for two degrees of freedom and
# they disagree by 3.1%; radius and span are the pair that fix real geometry, so the angle
# yields. Arc length and developed span now agree exactly by construction. The outer span is swept along this path; the brief is explicit that you
# BEND the geometry rather than cutting a tip off and gluing it on, or chord and thickness
# step at the joint.
#
# THE NUMBER THE BRIEF ASKS FOR: projected (swept-disc) radius after the bend is
#   {proj:.4f} R against a developed {1.0:.4f} R -> projected diameter {2*proj*QT['D']/2:.1f} mm vs {QT['D']:.0f} mm developed.
# That {(1-proj)*100:.1f}% disc reduction IS the trade: ground clearance and tip noise bought with disc area.
#
# r_developed is arc position along the blade; r_projected is the radius that actually sweeps.
# z_R is aft displacement as a fraction of R (negative = aft).""",
["u","r_developed_R","r_projected_R","z_R","bend_deg"], q)

# ----------------------------------------------------------- serrations ------
SR=dict(start=0.5, amp_c=0.05, wave_c=0.10, D=254.0)
# Wavelength is a fixed fraction of local chord, so the tooth COUNT per chord is the same
# at every station even though the tooth SIZE scales. Constant by construction.
TEETH_PER_CHORD = round(1/SR["wave_c"])
def serr(n=26):
    rows=[]
    for i in range(n):
        r=SR["start"]+(1-SR["start"])*i/(n-1)
        c=interp(APC, r)*SR["D"]                      # local chord in mm, from the real blade
        rows.append((r, c, SR["amp_c"]*c, SR["wave_c"]*c, TEETH_PER_CHORD))
    return rows
write("serrated","serration-schedule.csv",
f"""# Trailing-edge serration schedule - SYNTHETIC, GENERATED BY {GEN}
#
# NOT measured. Amplitude and wavelength are the brief's parameters, expressed as ratios of
# LOCAL chord. Reference for the concept: serrated TE for drone noise,
# https://www.sciencedirect.com/science/article/abs/pii/S0003682X25005171
#
# From the brief: applied over r/R {SR['start']} to the tip, amplitude {SR['amp_c']:.0%} and wavelength
# {SR['wave_c']:.0%} of local chord, saw-tooth or sinusoidal, optionally on the leading edge too.
#
# WHY RATIOS OF LOCAL CHORD MATTER: the brief warns the serration must be applied along the
# edge curve IN THE BLADE'S OWN SURFACE, following the twist - not as a cut through a flat
# plane, which would bite deeper at the root than at the tip. Scheduling amplitude off local
# chord is what keeps the serration proportionate along the span; the columns below give the
# actual mm at each station so that can be checked rather than assumed.
#
# Local chord is taken from the real APC 10x5E (../fixed-pitch/apc-10x5e.csv).
# Export the PLAIN blade alongside the serrated one - the brief asks for the pair so they can
# be compared on a thrust stand.""",
["r_R","chord_mm","amplitude_mm","wavelength_mm","teeth_per_chord"], serr())

# ------------------------------------------------------- toroidal loop -------
def catmull_rom(pts, n=120, alpha=0.5):
    """CENTRIPETAL Catmull-Rom (alpha=0.5) through the control points, closed.

    Uniform Catmull-Rom (alpha=0) overshoots between widely spaced control
    points: the first version of this path dipped to r/R 0.1338 against a hub
    control point of 0.18, i.e. the loop passed INSIDE the hub boss it attaches
    to. Centripetal parameterisation is the standard remedy - it provably
    produces no cusps and no self-intersection within a segment (Yuksel et al.,
    "Parameterization and Applications of Catmull-Rom Curves", CAD 43(7), 2011).
    check-aerial-geometry.py asserts the result stays outboard of the hub.
    """
    def tj(ti, pi, pj):
        d = math.dist(pi, pj)
        return ti + d**alpha
    def seg(p0, p1, p2, p3, t):
        t0 = 0.0; t1 = tj(t0, p0, p1); t2 = tj(t1, p1, p2); t3 = tj(t2, p2, p3)
        if t1 == t0 or t2 == t1 or t3 == t2: return p1
        t = t1 + (t2 - t1) * t
        def lerp(a, b, ta, tb, tt):
            return tuple(((tb-tt)/(tb-ta))*x + ((tt-ta)/(tb-ta))*y for x, y in zip(a, b))
        A1 = lerp(p0, p1, t0, t1, t); A2 = lerp(p1, p2, t1, t2, t); A3 = lerp(p2, p3, t2, t3, t)
        B1 = lerp(A1, A2, t0, t2, t); B2 = lerp(A2, A3, t1, t3, t)
        return lerp(B1, B2, t1, t2, t)
    # OPEN path, root -> tip -> root. The loop is closed BY THE HUB, not by a spline
    # segment: the brief says each blade "leaves the hub, loops, and returns". Splining
    # the closing segment made the curve cut through the hub region, which is what drove
    # r/R down to 0.13. Endpoints are duplicated to give the end segments a tangent.
    P = [pts[0]] + list(pts) + [pts[-1]]
    segs = len(P) - 3; per = max(n // segs, 2); out = []
    for i in range(segs):
        for k in range(per):
            out.append(seg(P[i], P[i+1], P[i+2], P[i+3], k/per))
    out.append(tuple(pts[-1]))
    return out
CTRL=[(0.18,-14.0,0.00),(0.55,-26.0,0.05),(1.00,0.0,0.09),(0.55,26.0,0.05),(0.18,14.0,0.00)]
loop=catmull_rom(CTRL,120)
write("toroidal","loop-path.csv",
f"""# Aerial toroidal loop path - SYNTHETIC, GENERATED BY {GEN}
#
# NOT copied from the Ultimate Toroidal Propeller Generator. That project
# (https://github.com/RaulBejarano/Ultimate-Toroidal-Propeller-Generator) is the brief's
# recommended starting point and it uses a Catmull-Rom spline through five control points -
# but it is GPL-3.0, and copying its code would put this repository under GPL. The METHOD
# (a Catmull-Rom spline) is generic mathematics and is implemented independently here; the
# control points are this repo's own. Credit to that project for the approach.
# MIT Lincoln Laboratory holds the reference toroidal design.
#
# The path runs ROOT -> TIP -> ROOT and is closed by the HUB, not by a spline segment. Both
# ends sit at r/R {CTRL[0][0]} on opposite sides ({CTRL[0][1]:+.0f} and {CTRL[-1][1]:+.0f} deg), which are the two root joints the
# brief asks for. Tangent continuity along the blade is a property of the spline, so it holds
# by construction - the brief's first Done-when.
#   r_R      radius, hub {CTRL[0][0]} out to the tip and back
#   theta    circumferential offset, deg - the two root joints sit at +/-{abs(CTRL[0][1]):.0f} deg
#   z_D      axial arch over the top of the loop
#
# NOT SETTLED HERE: whether the return branch clears the leading branch. That is a solid-model
# question - sweep the section, then test for self-intersection. A tangent-continuous
# centreline does not by itself guarantee a non-self-intersecting solid.
# Two or three loops per the brief: replicate at 180 or 120 deg about the axis.""",
["r_R","theta_deg","z_D"], loop)

# --------------------------------------------------- mechanical fits ---------
FOLD=dict(pin=3.0, offset=10.0, tang=3.0, fold_max=175.0)
rows=[]
for cls,lo,hi,note in [("H7/g6 close running",0.006,0.020,"preferred for a fold hinge"),
                       ("H7/f7 free running",0.016,0.041,"if grit ingress is likely"),
                       ("H8/d9 loose running",0.040,0.092,"only if the pin is retained axially")]:
    rows.append((cls, FOLD["pin"], FOLD["pin"]+lo, FOLD["pin"]+hi, lo, hi, note))
write("folding","hinge-fits.csv",
f"""# Folding blade hinge pin fits - SYNTHETIC, GENERATED BY {GEN}
#
# NOT transcribed from ISO 286. Those tolerance tables are the authoritative source and are
# not free; these are the standard running-clearance CLASSES with representative clearances
# for a {FOLD['pin']:.0f} mm pin. Check against ISO 286-2 before cutting metal.
#
# WHY IT MATTERS: the brief says "the pin bore is a clearance fit on the pin". A nominal
# {FOLD['pin']:.0f} mm bore on a {FOLD['pin']:.0f} mm pin does not turn - it is a line-to-line fit. The blade must
# swing freely through {FOLD['fold_max']:.0f} deg under its own inertia, so pick a running class.
#
# The brief's real constraint is elsewhere and no fit table fixes it: the blade's CENTRE OF
# MASS must sit outboard of the hinge pin, so spinning up deploys the blade and holds it
# against the stop. Get that wrong and the prop never opens, whatever the fit.
# Hinge offset {FOLD['offset']:.0f} mm from the rotation axis, root tang {FOLD['tang']:.0f} mm thick. All mm.""",
["fit_class","pin_dia_mm","bore_min_mm","bore_max_mm","clearance_min_mm","clearance_max_mm","note"], rows)

BRG=dict(shank=8.0, horn=6.0, collar=4.0, pitch_range=25.0)
rows=[("MR128", 8.0, 12.0, 3.5, "thin-section, lightest"),
      ("688",   8.0, 16.0, 5.0, "wider race, higher radial capacity"),
      ("608",   8.0, 22.0, 7.0, "standard skate bearing, heaviest")]
write("collective-pitch","bearing-bores.csv",
f"""# Collective pitch grip bearing options - SYNTHETIC, GENERATED BY {GEN}
#
# NOT a manufacturer's catalogue. These are the common metric deep-groove sizes with an
# {BRG['shank']:.0f} mm bore, which is what the brief's shank diameter fixes. Confirm dimensions and
# load ratings against SKF/NSK/NMB data before committing.
#
# From the brief: shank {BRG['shank']:.0f} mm, TWO bearing bores per grip, pitch horn offset {BRG['horn']:.0f} mm,
#   collar travel +/-{BRG['collar']:.0f} mm, pitch range +/-{BRG['pitch_range']:.0f} deg about the r/R = 0.75 setting.
#
# The bore is set by the shank, so the choice is really outer diameter and width - i.e. how
# much hub the grip needs. Two bearings per grip spaced apart is what reacts the blade's
# bending moment; a single bearing would let the blade cock under load.
# GEOMETRY CHECK the brief actually asks for: sweep collar_z over its +/-{BRG['collar']:.0f} mm and confirm
# the full +/-{BRG['pitch_range']:.0f} deg is reached with no link-to-hub interference at either stop. That is a
# kinematic check on the assembly, not something this table can answer.
# All mm.""",
["designation","bore_mm","outer_dia_mm","width_mm","note"], rows)

print("\nAll aerial geometry regenerated.")
